### ISSUE TITLE
Borderless Mining Not Working

### ISSUE THREAD

**Issue by leviFrosty** [Fabulously-Optimized/fabulously-optimized#769] opened 2023-11-20 22:37 UTC
### Describe the bug

Launch a new instance of the pack (fresh install) -> mods -> Bordless Mining -> Settings -> Set bordless fullscreen: ON -> Press F11

Expected: Borderless Fullscreen
Result: Standard Fullscreen

### Modpack version

5.5.1

### Launcher

MultiMC

### Confirm

- [X] This bug report is about an issue with the modpack itself, I have not modified the mods nor added any resource packs. If this is not the case, I know that I should post the issue to modpack's Discord support channel instead.

### Additional context

<img width="1920" alt="image" src="https://github.com/Fabulously-Optimized/fabulously-optimized/assets/79994715/81f70349-8add-4978-a2c8-e9d471e6aa88">

**Comment by Madis0** [comment] 2023-11-21 05:04
What OS? How do you see the difference?

**Comment by leviFrosty** [comment] 2023-11-21 05:21
> What OS? How do you see the difference?

I'm running Windows 11 Build 22621

I would expect Windowed Borderless to allow for instant alt-tabs, as it does with most other games. I do not see this experience, instead I get a long(er) black screen while the game becomes unfocused

**Comment by Madis0** [comment] 2023-11-21 09:07
Okay. I've asked a few people to test (one on Arch and one on Win11), and they cannot reproduce.

Try playing with only that mod enabled and if you still can reproduce, report it to the dev.

**Comment by Madis0** [comment] 2023-11-28 05:40
Can you still reproduce it with FO 5.6.0?

**Comment by Madis0** [comment] 2023-11-29 21:08
Seems like https://github.com/comp500/BorderlessMining/issues/88

**Comment by Madis0** [comment] 2024-03-20 15:04
#814 was added instead in 5.8.0, closing.

**Closed by Madis0** 2024-03-20 15:04 UTC
Labels: bug
