### ISSUE TITLE
Less loading time

### ISSUE THREAD

**Issue by Probattler** [Fabulously-Optimized/fabulously-optimized#263] opened 2022-03-15 22:35 UTC
### Mod name

kennytvs-epic-force-close-loading-screen-mod-for-fabric

### Other links

https://modrinth.com/mod/forcecloseworldloadingscreen

### What it does

Since 1.18.2, the client only quits the world loading screen once the chunk it is in has been received... [and at least 2 seconds have passed](https://bugs.mojang.com/browse/MC-249059).

By default, the mod fixes that behavior. Additionally, you can also fully get rid of the screen

### Why should it be in the modpack

Seems very promising, speeds up the process of world / server loading. 

### Why shouldn't it be in the modpack

Not available on curseforge. 

### Categories

New feature

**Comment by Madis0** [comment] 2022-03-16 03:57
Duplicate of #261 😄

**Closed by Madis0** 2022-03-16 03:57 UTC
Labels: mod
