### ISSUE TITLE
Nvidium should be added

### ISSUE THREAD

**Issue by AndrewEllen** [Fabulously-Optimized/fabulously-optimized#875] opened 2024-08-15 04:08 UTC
### CurseForge Mod Distribution

Unknown

### Modrinth link

https://modrinth.com/mod/nvidium

### Mod file size

153.71

### License

(any other license)

### What it does

Nvidium uses mesh shaders to improve chunk loading performance through GPU Hardware Acceleration. Currently, the mod only works on Nvidia GPUs (16xx series and RTX series) but will disable itself on when Nvidia hardware is not detected. AMD has plans to support mesh shaders by the end of this year which means future support may become available on AMD systems. The mod also disables itself when shaders are enabled however when shaders are not enabled it increases framerate stability and overall framerate. On higher render distances the difference is much more noticeable.

### Why should it be in the modpack

It should be added to the pack because it greatly increases stability and performance for computers that support it. It is actively in development and up to date. It is relatively bug-free, I have had zero crashes from Nvidium from an entire year of using it in various mod packs from Wynncraft to heavily modded packs and my friends have had the same experience. 

Because it disables itself when it doesn't have the necessary hardware and software support it is not detrimental to the playability of the modpack. When someone has a system that can use it their games framerate performance will see massive gains.

### Why shouldn't it be in the modpack

The mod is currently in a beta version so while it is quite bug-free there may still be a few issues for certain systems that haven't been found yet.

**Comment by Madis0** [comment] 2024-08-15 04:55
Duplicate of #752.

**Closed by Madis0** 2024-08-15 04:55 UTC
Labels: mod
