### ISSUE TITLE
Bobby 

### ISSUE THREAD

**Issue by EquityX** [Fabulously-Optimized/fabulously-optimized#556] opened 2022-12-27 03:31 UTC
### CurseForge link

https://www.curseforge.com/minecraft/mc-mods/bobby

### CurseForge Mod Distribution

Allowed

### Modrinth link

https://modrinth.com/mod/bobby

### Source/other link

https://github.com/Johni0702/bobby

### Mod file size

770.05 KB

### License

(any other license)

### What it does

Bobby is a Minecraft mod which allows for render distances greater than the server's view-distance setting.

### Why should it be in the modpack

I was having chunks just stop loading until I reload the world. This happened on multiple different modpacks & worlds. It turns out the culprit was Farsight. Even if Farsight wasn't loading any fake chunks it would still cause this problem.

Bobby has had a major update that removed all the stuttering & lag for me that it had before. I've been using it instead of Farsight now & haven't had a single problem. The performance is even improved over Farsight by a lot & Bobby has the benefit of remembering chunks without re exploring them which is a huge plus. Bobby also works in singleplayer & can be configured in the in game menu.

Hold That Chunk Fabulously Optimized 4.5.5 32 Render Distance V sync off
![Hold That Chunk](https://user-images.githubusercontent.com/20719360/209653972-554ff296-1516-43d4-807b-6fc92b73ee38.png)

Farsight Fabulously Optimized 4.5.5 32 Render Distance V sync off
![Farsight 32](https://user-images.githubusercontent.com/20719360/209605856-74e7f0e5-a337-47a0-88ff-4ca3eb2dcded.png)

Bobby Fabulously Optimized 4.5.5 32 Render Distance V sync off
![Bobby 32](https://user-images.githubusercontent.com/20719360/209605960-ad7cb7f4-3988-47b0-8c81-815561e0512e.png)

All mods & settings are 100% identical. I only swapped Farsight for Bobby.

### Why shouldn't it be in the modpack

Worlds can have mixed chunks on minigame servers. I am currently testing some solutions to see if this can be solved.

### Additional details

I suggest setting the singleplayer server view distance to 12 max so players can benefit from extra performance if they exceed 12 view distance in singleplayer.

**Comment by Madis0** [comment] 2022-12-27 05:35
Duplicate of #46

**Comment by Madis0** [comment] 2022-12-27 05:44
Actually, let's have a fresh one.

**Comment by Julienraptor01** [comment] 2022-12-27 07:56
> Actually, let's have a fresh one. Have you tested Bobby against Hold That Chunk? Do that and let me know.

I do, Bobby is even wore than farsight and hold that chunk because it doesn't recognize correctly world change from minigames servers and you end up with mixed world
(by example go in hypixel skyblock in the hub, explore it then come back to your Island and see that far chunks are actually the hub chunks)

**Comment by EquityX** [comment] 2022-12-27 21:56
Farsight doesn't have the mixed world issue because it doesn't remember chunks at all when world changing. So it is a choice between remembering no chunks when world changing or the wrong chunks when it comes to Bobby. Personally I prefer the mixed chunks as either way you have to re explore the chunks to get them back/correct them & I think the additional benefits from Bobby are worth it. Setting your render distance to the server value will fix the mixed chunks by removing the need for fake chunks, essentially disabling the mod.

I also added results for Hold That Chunk.

**Comment by Julienraptor01** [comment] 2022-12-27 22:04
> Farsight doesn't have the mixed world issue because it doesn't remember chunks at all when world changing. So it is a choice between remembering no chunks when world changing or the wrong chunks when it comes to Bobby. Personally I prefer the mixed chunks as either way you have to re explore the chunks to get them back/correct them & I think the additional benefits from Bobby are worth it. Setting your render distance to the server value will fix the mixed chunks by removing the need for fake chunks, essentially disabling the mod.
> 
> I also added results for Hold That Chunk.

Well if you mostly only play in one or 2 worlds it isn't a too big of a problem but if you play on minigames based servers or in lobby based ones it get really weird and would be seen as a very big issue for many people

**Comment by osfanbuff63** [comment] 2022-12-27 22:10
Here's a couple reasons why I would lean on the side of not adding this:

- Bobby vs Farsight was decided by a [public vote](https://github.com/Fabulously-Optimized/fabulously-optimized/issues/46#issuecomment-1079896968), however that hasn't stopped us from testing #437.
- The issue mentioned above - on minigames servers where proxies are used to generate new void worlds every time I can't imagine that solution being helpful
- A theoretical performance loss by disabling huge caches. Those caches were mentioned as being a reason to not include it in #46, as taking up tons of storage space isn't ideal.

**Comment by Kichura** [comment] 2022-12-28 00:52
+ Bobby has been known for causing world loading corruption so it looks like the main spawn is loaded but outside of it causes it to generate fake chunks from other places; in this case, i see this as being not-so-great to implement even if people tell this otherwise.

**Comment by Madis0** [comment] 2022-12-28 05:31
If Bobby will be added, the world caching _will_ be disabled by default.

**Comment by RaptaG** [comment] 2023-01-02 13:20
I suggest the next alpha or beta FO release include Bobby for testing in the Modrinth version and then do a comparison with the two mods, just like we did with Bobby vs Farsight.

**Comment by osfanbuff63** [comment] 2023-01-02 13:40
That may or may not be a great idea, given that Modrinth versions are now fully supported and Prism relies on Modrinth - which based on the Discord roles isn't an insignificant of our over 1.1k Discord users. Not to mention our number of Modrinth downloads skyrocketing since Prism support was added...

![image](https://user-images.githubusercontent.com/91388253/210238973-bd1c9a10-8188-4b68-8685-1985ba902530.png)

![image](https://user-images.githubusercontent.com/91388253/210238953-b4b2c199-48a9-4154-8ca4-6bfb805d2326.png)

**Comment by lynrayy** [comment] 2023-01-13 18:50
Incompatible with fabulously optimized now :(

**Comment by lynrayy** [comment] 2023-01-13 19:02
Im trying to install bobby mod with this modpack and got this: 
![image](https://user-images.githubusercontent.com/59417884/212398467-3b05109c-35ac-4e80-95b7-7dc5042fd17f.png)

**Comment by PoorPocketsMcNewHold** [comment] 2023-01-14 20:26
> [**@lynrayy**](https://github.com/lynrayy) commented on [Jan 13, 2023, 6:50 PM UTC](https://github.com/Fabulously-Optimized/fabulously-optimized/issues/556#issuecomment-1382247387):
> 
> > Incompatible with fabulously optimized now :(
> > 
> > _Originally posted by @lynrayy in https://github.com/Fabulously-Optimized/fabulously-optimized/issues/556#issuecomment-1382247387_

It still work fine for me. Remember to disable/remove Hold that Chunk, as it conflict with it, due to achieving "similar" results.

**Comment by RaptaG** [comment] 2023-04-23 07:41
There now is a patch for the multi-world issue, but the dev needs testers. More information here:
https://github.com/Johni0702/bobby/issues/72#issuecomment-1518831417

**Comment by Julienraptor01** [comment] 2023-04-23 07:44
> There now is a patch for the multi-world issue, but the dev needs testers. More information here:
> https://github.com/Johni0702/bobby/issues/72#issuecomment-1518831417

I guess i'm temporarily switch from HTC to Bobby to see how it goes

**Comment by Madis0** [comment] 2023-09-14 19:34
Will not be included per https://github.com/Fabulously-Optimized/fabulously-optimized/issues/656#issuecomment-1720029606 .

**Closed by Madis0** 2023-09-14 19:34 UTC
Labels: mod, parity, replace
