### ISSUE TITLE
Enable Adaptive Sync

### ISSUE THREAD

**Issue by RaptaG** [Fabulously-Optimized/fabulously-optimized#431] opened 2022-08-02 19:46 UTC
### What config to change

As said by the title, disable VSync and and enable Adaptive VSync (`Extras` tab)

### Why should it be changed

People are constantly reporting that they are getting no FPS improvements while using FO and most of the times it's because of that. Some examples are:
- https://discord.com/channels/859124104644788234/859124571005648946/1004097034887901194
- https://discord.com/channels/859124104644788234/859124571005648946/1002938224987078697
- https://discord.com/channels/859124104644788234/893444857929023558/1003833242522234922

(from the Discord server: https://discord.gg/yxaXtaQqdB)

Doing this will improve frame rates while having stability

### Category

Vanilla option

### Additional details

Enabling Adaptive VSync is a solution to potential drawbacks of disabling VSync itself. See:
https://www.intel.com/content/www/us/en/developer/articles/technical/enabling-intel-adaptive-sync-with-11th-generation-intel-processor-graphics-and-microsoft.html

**Comment by Madis0** [comment] 2022-08-02 19:49
I get the idea, but what to do for people who don't have Adaptive Vsync?

**Comment by RaptaG** [comment] 2022-08-02 19:50
> I get the idea, but what to do for people who don't have Adaptive Vsync?

Which people _dont' have_ Adaptive VSync?

**Comment by Madis0** [comment] 2022-08-02 19:52
I don't, for example.

**Comment by RaptaG** [comment] 2022-08-02 19:53
> I don't, for example.

I mean, is it something with the hardware?

**Comment by Madis0** [comment] 2022-08-02 19:53
Yes, it is available only when supported by the hardware.

**Comment by Zetsphiron** [comment] 2022-08-02 20:01
It is a hardware thing, more specifically if your monitor supports it

**Comment by Julienraptor01** [comment] 2022-08-02 20:17
> ### What config to change
> 
> As said by the title, disable VSync and and enable Adaptive VSync (`Extras` tab)
> 
> ### Why should it be changed
> 
> People are constantly reporting that they are getting no FPS improvements while using FO and most of the times it's because of that. Some examples are:
> - https://discord.com/channels/859124104644788234/859124571005648946/1004097034887901194
> - https://discord.com/channels/859124104644788234/859124571005648946/1002938224987078697
> - https://discord.com/channels/859124104644788234/893444857929023558/1003833242522234922
> 
> (from the Discord server: https://discord.gg/yxaXtaQqdB)
> 
> Doing this will improve frame rates while having stability
> 
> ### Category
> 
> Vanilla option
> 
> ### Additional details
> 
> Enabling Adaptive VSync is a solution to potential drawbacks of disabling VSync itself. See:
> https://www.intel.com/content/www/us/en/developer/articles/technical/enabling-intel-adaptive-sync-with-11th-generation-intel-processor-graphics-and-microsoft.html 

I say no to this but inform people that if they can do it they should do it

**Comment by Julienraptor01** [comment] 2022-08-02 20:21
We should do multiple really simple polls to get some ideas of numbers
1st : Do you have access to adaptive sync ?
If it's greyed out under the extra tab, the response is not.
2nd : If you don't have access to A-sync, do you have tearing with Vsync disabled ?

**Comment by isXander** [comment] 2022-08-02 20:58
Can't you turn on both? A-sync will override vsync? Internally it's the same glfw property

**Comment by Julienraptor01** [comment] 2022-08-02 21:00
> Can't you turn on both? A-sync will override vsync? Internally it's the same glfw property

Are you sure it will Override ? Maybe we should ask @FlashyReese to be sure

**Comment by FlashyReese** [comment] 2022-08-02 21:23
Adaptive Sync needs V-Sync on to work

**Comment by Julienraptor01** [comment] 2022-08-02 21:25
> Adaptive Sync needs V-Sync on to work

Could add that smth like "Require Vsync enabled to work !" in Adaptive sync tooltip ?

**Comment by FlashyReese** [comment] 2022-08-02 21:27
> > Adaptive Sync needs V-Sync on to work
> 
> Could add that smth like "Require Vsync enabled to work !" in Adaptive sync tooltip ?

Sorry, my bad. It overrides.

**Comment by Julienraptor01** [comment] 2022-08-02 21:30
> > > Adaptive Sync needs V-Sync on to work
> > 
> > 
> > Could add that smth like "Require Vsync enabled to work !" in Adaptive sync tooltip ?
> 
> Sorry, my bad. It overrides.

ok so it's confirmed either A-sync or Vsync need to be enabled, not both at same time.
Could you make it so that A-sync override Vsync ? I actually don't know if this is in your power or if it's a thing just that you couldn't even control.

**Comment by FlashyReese** [comment] 2022-08-02 21:32
> > > > Adaptive Sync needs V-Sync on to work
> > > 
> > > 
> > > Could add that smth like "Require Vsync enabled to work !" in Adaptive sync tooltip ?
> > 
> > 
> > Sorry, my bad. It overrides.
> 
> ok so it's confirmed either A-sync or Vsync need to be enabled, not both at same time. Could you make it so that A-sync override Vsync ? I actually don't know if this is in your power or if it's a thing just that you couldn't even control.

I'm so sorry, my brain is on autopilot and just typing out random stuff. It needs Vsync to work if not it just fallbacks to whatever state vsync is in. Adaptive Sync should not be enabled by default. Not all machines support it. I need to add another layer of checks to prevent it from being enabled via config.

**Comment by Julienraptor01** [comment] 2022-08-02 21:38
> > > > > Adaptive Sync needs V-Sync on to work
> > > > 
> > > > 
> > > > Could add that smth like "Require Vsync enabled to work !" in Adaptive sync tooltip ?
> > > 
> > > 
> > > Sorry, my bad. It overrides.
> > 
> > 
> > ok so it's confirmed either A-sync or Vsync need to be enabled, not both at same time. Could you make it so that A-sync override Vsync ? I actually don't know if this is in your power or if it's a thing just that you couldn't even control.
> 
> I'm so sorry, my brain is on autopilot and just typing out random stuff. It needs Vsync to work if not it just fallbacks to whatever state vsync is in. Adaptive Sync should not be enabled by default. Not all machines support it. I need to add another layer of checks to prevent it from being enabled via config.

Well if it's enabled via config but not available it'll simply disable itself right ?

**Comment by FlashyReese** [comment] 2022-08-02 21:41
> > > > > > Adaptive Sync needs V-Sync on to work
> > > > > 
> > > > > 
> > > > > Could add that smth like "Require Vsync enabled to work !" in Adaptive sync tooltip ?
> > > > 
> > > > 
> > > > Sorry, my bad. It overrides.
> > > 
> > > 
> > > ok so it's confirmed either A-sync or Vsync need to be enabled, not both at same time. Could you make it so that A-sync override Vsync ? I actually don't know if this is in your power or if it's a thing just that you couldn't even control.
> > 
> > 
> > I'm so sorry, my brain is on autopilot and just typing out random stuff. It needs Vsync to work if not it just fallbacks to whatever state vsync is in. Adaptive Sync should not be enabled by default. Not all machines support it. I need to add another layer of checks to prevent it from being enabled via config.
> 
> Well if it's enabled via config but not available it'll simply disable itself right ?

Nope, this check is only done via the GUI. The feature was directly picked from https://github.com/CaffeineMC/sodium-fabric/pull/1194.

**Comment by Julienraptor01** [comment] 2022-08-02 22:09
OK i ran Quick Tests on my High-end PC which has a 240Hz panel which support A-sync
Type of sync : MAX / Avg / min
A-sync : 210 / 205 / 200
Vsync : 220 / 200 / 170
No sync : 240 / 237 / 233

**Comment by Julienraptor01** [comment] 2022-08-02 22:10
> > > > > > > Adaptive Sync needs V-Sync on to work
> > > > > > 
> > > > > > 
> > > > > > Could add that smth like "Require Vsync enabled to work !" in Adaptive sync tooltip ?
> > > > > 
> > > > > 
> > > > > Sorry, my bad. It overrides.
> > > > 
> > > > 
> > > > ok so it's confirmed either A-sync or Vsync need to be enabled, not both at same time. Could you make it so that A-sync override Vsync ? I actually don't know if this is in your power or if it's a thing just that you couldn't even control.
> > > 
> > > 
> > > I'm so sorry, my brain is on autopilot and just typing out random stuff. It needs Vsync to work if not it just fallbacks to whatever state vsync is in. Adaptive Sync should not be enabled by default. Not all machines support it. I need to add another layer of checks to prevent it from being enabled via config.
> > 
> > 
> > Well if it's enabled via config but not available it'll simply disable itself right ?
> 
> Nope, this check is only done via the GUI. The feature was directly picked from [CaffeineMC/sodium-fabric#1194](https://github.com/CaffeineMC/sodium-fabric/pull/1194).

Should i make an issue in sodium-extra to add the requirement to A-sync tooltip ?

**Comment by FlashyReese** [comment] 2022-08-02 22:54
> Should i make an issue in sodium-extra to add the requirement to A-sync tooltip ?
Should i also make another issue to add this behavior of disabling A-sync tautomatically if it's unsupported ?
If this behavior is added it would mean that FO can just enable A-sync and Vsync and people who can't use A-sync fall back to Vsync.

That won't be necessary, I've already pushed a fix for machines that don't support it and has it enabled via config. This will be available in the next release. I might replace that VSync control to cycle between `None, VSync and Adaptive Sync`.

**Comment by Julienraptor01** [comment] 2022-08-02 23:04
> > Should i make an issue in sodium-extra to add the requirement to A-sync tooltip ?
> > Should i also make another issue to add this behavior of disabling A-sync tautomatically if it's unsupported ?
> > If this behavior is added it would mean that FO can just enable A-sync and Vsync and people who can't use A-sync fall back to Vsync.
> 
> That won't be necessary, I've already pushed a fix for machines that don't support it and has it enabled via config. This will be available in the next release. I might replace that VSync control to cycle between `None, VSync and Adaptive Sync`.

That would fix both problems at the same time
If you don't have A-sync but is on it on the config could it go back to Vsync automatically ?

**Comment by comp500** [comment] 2022-08-03 01:03
Note that the VESA Adaptive Sync standard for variable refresh rate displays (or proprietary technologies G-SYNC/FreeSync) is ***not*** the same as the "Adaptive *VSync*" (NVIDIA's term, AMD seems to call it Enhanced Sync) controlled by `WGL_EXT_swap_control_tear` that Sodium Extra enables. It appears to be fairly widely supported in terms of GPU vendors, and doesn't require explicit monitor support, but is not as effective as Adaptive Sync technologies. I believe that users with variable refresh rate displays just need to disable VSync for Adaptive Sync to work, though this may depend on GPU drivers.

**Comment by Julienraptor01** [comment] 2022-08-03 06:37
> Note that the VESA Adaptive Sync standard for variable refresh rate displays (or proprietary technologies G-SYNC/FreeSync) is ***not*** the same as the "Adaptive *VSync*" (NVIDIA's term, AMD seems to call it Enhanced Sync) controlled by `WGL_EXT_swap_control_tear` that Sodium Extra enables. It appears to be fairly widely supported in terms of GPU vendors, and doesn't require explicit monitor support, but is not as effective as Adaptive Sync technologies. I believe that users with variable refresh rate displays just need to disable VSync for Adaptive Sync to work, though this may depend on GPU drivers.

Require to disable Vsync for which Adaptive Sync to work ? That one from sodium extra ? Or the other ? Because from what i tested A-sync from SE do need Vsync enabled.

**Comment by FlashyReese** [comment] 2022-08-03 06:42
> Require to disable Vsync for which Adaptive Sync to work ? That one from sodium extra ? Or the other ? Because from what i tested the A-sync from SE do need Vsync enabled.

It doesn't need "vsync" to work. It can be written to work without vsync being enabled. It's just been picked and has never been modified from the original PR.

**Comment by Julienraptor01** [comment] 2022-08-03 07:09
> > Require to disable Vsync for which Adaptive Sync to work ? That one from sodium extra ? Or the other ? Because from what i tested the A-sync from SE do need Vsync enabled.
> 
> It doesn't need "vsync" to work. It can be written to work without vsync being enabled. It's just been picked and has never been modified from the original PR.
> 

Yeah i didn't meant like the technology need the other technology, i mean that here you need both options to be enabled. If you only have A-sync it doesn't do anything.

**Comment by Julienraptor01** [comment] 2022-08-03 08:12
@RaptaG should change name to simply "Enable Adaptive Sync"
Because Vsync needs to be enabled in options.
This might get a bit obsolete once next version of sodium extra is released due to [that](https://media.discordapp.net/attachments/1004113172397039666/1004293284992135231/unknown.png)

**Comment by RaptaG** [comment] 2022-08-03 09:13
> @RaptaG should change name to simply "Enable Adaptive Sync"

👍

**Comment by Madis0** [comment] 2022-08-03 19:05
So the idea is to wait for the next Sodium Extra, which will add additional checks for the feature, and still enable Adaptive Vsync by default in FO?

**Comment by Zetsphiron** [comment] 2022-08-04 04:33
> Note that the VESA Adaptive Sync standard for variable refresh rate displays (or proprietary technologies G-SYNC/FreeSync) is _**not**_ the same as the "Adaptive _VSync_" (NVIDIA's term, AMD seems to call it Enhanced Sync) controlled by `WGL_EXT_swap_control_tear` that Sodium Extra enables. It appears to be fairly widely supported in terms of GPU vendors, and doesn't require explicit monitor support, but is not as effective as Adaptive Sync technologies. I believe that users with variable refresh rate displays just need to disable VSync for Adaptive Sync to work, though this may depend on GPU drivers.

Alright, so if my machine claims on a sticker that it has "Adaptive Sync", how would I make sure it also has NVIDIA's standard, considering it has a recent NVIDIA card?


> @RaptaG should change name to simply "Enable Adaptive Sync" Because Vsync needs to be enabled in options. This might get a bit obsolete once next version of sodium extra is released due to [that](https://discord.com/channels/859124104644788234/1004113172397039666/1004293285818404926) : ![unknown.png](https://user-images.githubusercontent.com/49841713/182558819-6355e5e5-15d9-4a7f-995e-24968e8df651.png) And when that is released we can just enable A-sync and it'll fall back to Vsync for users that can't have A-sync.

Amazing! Gotta love those QoL revisions

**Comment by Julienraptor01** [comment] 2022-08-04 06:19
> So the idea is to wait for the next Sodium Extra, which will add additional checks for the feature, and still enable Adaptive Vsync by default in FO?

Yes

**Comment by Julienraptor01** [comment] 2022-08-04 06:37
> > Note that the VESA Adaptive Sync standard for variable refresh rate displays (or proprietary technologies G-SYNC/FreeSync) is _**not**_ the same as the "Adaptive _VSync_" (NVIDIA's term, AMD seems to call it Enhanced Sync) controlled by `WGL_EXT_swap_control_tear` that Sodium Extra enables. It appears to be fairly widely supported in terms of GPU vendors, and doesn't require explicit monitor support, but is not as effective as Adaptive Sync technologies. I believe that users with variable refresh rate displays just need to disable VSync for Adaptive Sync to work, though this may depend on GPU drivers.
> 
> Alright, so if my machine claims on a sticker that it has "Adaptive Sync", how would I make sure it also has NVIDIA's standard, considering it has a recent NVIDIA card?
> 

From what i read on internet G-sync is supported on all NVIDIA GPU at starting from series 10.
And for the Adaptive Sync that we can enable in sodium extra just check in it if currently you can enable it.
After researching more it seems like Adaptive VSync is a quite old technology.
NVIDIA decided to remove some pages about it but webarchive helped me.
https://web.archive.org/web/20210917033925/https://www.nvidia.com/en-us/geforce/technologies/adaptive-vsync/supported-gpus/
From what i can see Adaptive VSync compatible card listed here are only Pre-series 10 so i think NVIDIA just replaced it with G-sync but all new cards are just compatible with Adaptive VSync too.

**Comment by comp500** [comment] 2022-08-07 14:21
Adaptive VSync (not Adaptive Sync / G-SYNC / FreeSync) is usually implemented in the driver, and has very wide support across vendors. That list was likely not kept up to date; [all 10-series cards support it](https://opengl.gpuinfo.org/listreports.php?extension=WGL_EXT_swap_control_tear).

**Comment by HyperSoop** [comment] 2022-08-07 14:30
> Adaptive VSync (not Adaptive Sync / G-SYNC / FreeSync) is usually implemented in the driver, and has very wide support across vendors. That list was likely not kept up to date; [all 10-series cards support it](https://opengl.gpuinfo.org/listreports.php?extension=WGL_EXT_swap_control_tear).

Not only the 10-series: the oldest card to support it there is the 710 (the 705 being left out), so it's pretty much all of the 7-series.

**Comment by isXander** [comment] 2022-08-07 14:30
If I'm correct, it's just VSYNC that disables itself when fps over monitor refresh rate?

**Comment by comp500** [comment] 2022-08-08 17:28
> If I'm correct, it's just VSYNC that disables itself when fps under monitor refresh rate?

I think so, yes.

**Comment by RaptaG** [comment] 2022-08-19 16:19
The update with change of Adaptive Sync's placement on Sodium Extra has been released.

**Comment by Zetsphiron** [comment] 2022-08-19 22:08
> The update with change of Adaptive Sync's placement on Sodium Extra has been released.

Amazing! As an extra, I didn't notice much difference (on the previous release so far) in frame responsiveness using the adaptive sync checkmark while running Linux. I am using X11, and will do further tests on Linux and Windows with the new release soon.

**Closed** 2022-08-27 08:54 UTC
Labels: option

**Comment by Madis0** [comment] 2022-08-30 16:45
Added in 3.13.0 and 4.2.0, but reverted in 3.13.1 and 4.2.1 because of issues with some graphics drivers.

[Source](https://discord.com/channels/602796788608401408/752637878462578778/1013299011089874955) [(via)](https://caffeinemc.net/discord)
