### ISSUE TITLE
Cape mod freezes the game on large servers

### ISSUE THREAD

**Issue by Lalit64** [Fabulously-Optimized/fabulously-optimized#494] opened 2022-10-12 15:51 UTC
### Describe the bug

As it says in the title on any server I try to join after a few seconds the game just freezes. I've also found out that when I join any gamemode on Hypixel the game seems to freeze. This also happens when joining a game.

### Modpack version

4.4.1

### Launcher

CurseForge Launcher

### Other things

- [ ] I updated FO to a newer version (mention, what version to what version)
- [X] I added/removed some mods or resource packs (mention, which ones)

### Additional context

Apple Skin, Axolotl Bucket Fix, Better Advancements Better Mount HUD, Blur, Boosted Brightness, Controlling, Dark Loading Screen, Dash Loader, Enchantment Descriptions, Enhanced Attack Indicator, Equipment Compare, Essential Commands, ESSENTIAL Mod, Exordium (Installed after bug started occuring), Falling Leaves, Forge Config API, Illuminations, Inventory HUD+, Item Model Fix, Jade, Mini HUD, Mouse Tweaks, NotEnoughtAnimations, Skin Layers 3D, spark, Sword Blocking, Visuality, WorldEdit, Xaero's Minimap and Worldmap are all mods that I have installed.

Resource packs

My Vanilla Tweaks, Connected Polished Stones, TheWildUpdate (Just changes main menu), Illuminations resource packs.

M1 Pro Macbook Pro

Minecraft Version 1.19.2

**Comment by Madis0** [comment] 2022-10-12 16:02
- First, make a clean instance of FO without all of your additional mods, so we can confirm the issue is indeed happening only for you (seems very likely)
- That said, I would meet try to disable mods that affect _players_, due to the abundance of those in Hypixel. Most importantly, Essential mod
- You have spark, so I assume you know how to use it. Perhaps you could just make a debug report for yourself and read it to find your problem. Or if not, make it and post it here.
- _latest.log_ would be helpful

**Comment by Lalit64** [comment] 2022-10-13 06:45
Thanks. Happened to be ESSENTIAL Mod. I will file an issue on Essential's side.

**Comment by Lalit64** [comment] 2022-10-13 06:59
Never Mind it still seems to be happening.

**Comment by Lalit64** [comment] 2022-10-13 07:06
[latest.log](https://github.com/Fabulously-Optimized/fabulously-optimized/files/9771684/latest.log)

**Comment by Lalit64** [comment] 2022-10-13 14:47
Just tested an clean install without anything including resource packs and it is still freezing on occasions.

**Comment by Julienraptor01** [comment] 2022-10-13 15:13
> Just tested an clean install without anything including resource packs and it is still freezing on occasions.

On clean install does it freeze on hypixel only or on everything ?

**Comment by Lalit64** [comment] 2022-10-14 05:16
On everything.

**Comment by Madis0** [comment] 2022-10-14 09:09
> [latest.log](https://github.com/Fabulously-Optimized/fabulously-optimized/files/9771684/latest.log)

That log is not in a clean install. Try making a clean install of FO 4.4.2 and send logs again. Also try reducing video settings and maybe allocate more RAM.

**Comment by HyperSoop** [comment] 2022-10-15 06:07
Remove capes mod, I think the issue with the client freezing on Hypixel/etc when Lithium is there with it on hasn't been resolved yet.

**Comment by Lalit64** [comment] 2022-10-15 09:33
> 

Let me try that

**Comment by Lalit64** [comment] 2022-10-15 11:44
Seems to be the capes mod. Tested this for around an hour and not crashing at all.

**Comment by Madis0** [comment] 2022-10-15 11:52
Well, per the issue HyperSoop linked, I have already disabled all those providers in FO. But I guess it may be caused by the mod it self as well.

**Comment by Endninja137** [comment] 2022-10-21 16:19
I know that this isn't the right place to ask this, but I couldn't find anywhere else to. How did you get Sodium and Starlight to work together? Starlight is listed as "completely incompatible" with Sodium on both Curseforge and Modrinth. What's the secret?

**Comment by Madis0** [comment] 2022-10-21 16:29
> I know that this isn't the right place to ask this, but I couldn't find anywhere else to. How did you get Sodium and Starlight to work together? Starlight is listed as "completely incompatible" with Sodium on both Curseforge and Modrinth. What's the secret?

Starlight is incompatible with Phosphor, not Sodium. But please ask those questions here: https://discord.gg/yxaXtaQqdB

**Comment by Endninja137** [comment] 2022-10-21 19:54
Thanks!

**Comment by CaelTheColher** [comment] 2022-12-15 00:48
Should be fixed in Capes version 1.5.1 for 1.19.3.

Would appreciate if someone else could confirm it independently just in case.

**Closed** 2023-03-25 13:11 UTC
Labels: bug
