### ISSUE TITLE
entity collision fps fix

### ISSUE THREAD

**Issue by arichorn** [Fabulously-Optimized/fabulously-optimized#406] opened 2022-07-09 04:51 UTC
### CurseForge link

https://www.curseforge.com/minecraft/mc-mods/entity-collision-fps-fix-fabric

### CurseForge Mod Distribution

Allowed

### Modrinth link

https://modrinth.com/mod/entity-collision-fps-fix

### Source/other link

https://github.com/CorgiTaco/No-Client-Side-Entity-Collision-Checks

### What it does

Client side FPS optimization mod that skips collision checks on the client's render thread because these check are already handled by the server. FPS currently suffers because the client calculates collisions for seen and unseen entities. When a lot of entities are present and tightly packed together, this issue is far more severe. Running this mod, expect an FPS improvement in areas with loads of entities. (copy and pasted)

This mod aims to fix: https://bugs.mojang.com/browse/MC-228976 which has been confirmed on the bug tracker via community consensus.

### Why should it be in the modpack

it fixes one of the minecraft bugs that eat up your FrameRate and is a good addition for a mod like this to fix a pretty bad bug from minecraft.

### Why shouldn't it be in the modpack

if any of the mods already have this then there isn't any point of adding this then.

### Categories

Performance optimization, Fixes a bug/makes another mod work

### Additional details

I pretty much don't know what else to say.

**Comment by Madis0** [comment] 2022-07-09 06:25
Duplicate of #350

**Closed by Madis0** 2022-07-09 06:25 UTC
Labels: mod
