### ISSUE TITLE
Add Exordium

### ISSUE THREAD

**Issue by LCBOI** [Fabulously-Optimized/fabulously-optimized#640] opened 2023-04-27 00:45 UTC
### CurseForge link

https://www.curseforge.com/minecraft/mc-mods/exordium

### CurseForge Mod Distribution

Allowed

### Modrinth link

https://modrinth.com/mod/exordium

### Mod file size

121.02 KB

### License

All Rights Reserved / ARR

### What it does

It improves the fps by setting the gui at a lower framerate,so it can focus more on world rendering.

### Why should it be in the modpack

It improves framerate.

### Why shouldn't it be in the modpack

It limits the gui at a lower framerate,so it's looks laggy.

### Additional details

Nothing

**Comment by Madis0** [comment] 2023-04-27 03:55
Duplicate of #398

**Closed by Madis0** 2023-04-27 03:55 UTC
Labels: mod
