### ISSUE TITLE
Entity Collision FPS Fix

### ISSUE THREAD

**Issue by Izov4r** [Fabulously-Optimized/fabulously-optimized#585] opened 2023-02-11 21:35 UTC
### CurseForge link

https://www.curseforge.com/minecraft/mc-mods/entity-collision-fps-fix-fabric

### CurseForge Mod Distribution

Allowed

### Modrinth link

https://modrinth.com/mod/entity-collision-fps-fix

### Source/other link

https://youtu.be/iMg0jRpltXY

### Mod file size

~11KB

### License

All Rights Reserved / ARR

### What it does

Client side FPS optimization mod that skips collision checks on the client's render thread because these check are already handled by the server. FPS currently suffers because the client calculates collisions for seen and unseen entities. When a lot of entities are present and tightly packed together, this issue is far more severe. Running this mod, expect an FPS improvement in areas with loads of entities. Below is a video showing the FPS difference of removing these collision checks on my PC. This mod aims to fix: [https://bugs.mojang.com/browse/MC-228976](https://bugs.mojang.com/browse/MC-228976) which has been confirmed on the bug tracker via community consensus.

### Why should it be in the modpack

It won't even be noticed by most of the players ( unless they are geeks like me (and whoever is reading this post _(nested brackets, pretty cool, right?)_) opening [git](https://github.com/Fabulously-Optimized) ).
All it does is 'Entity Collision Fix' ( I think it is self-explanatory ) especially when using a mob farm.

### Why shouldn't it be in the modpack

It's available on both CurseForge and Modrinth, and has no downsides. There should be absolutely no reason for this to be a downside ( unless it is some incompatibility my 2 iq brain cannot see )

### Additional details

I have used this mod with literally all the mods used in Fabulously Optimized, and have had no issue,

**Unrelated:** An alternative to 'CustomFog' in older versions of Fabulously Optimized would be '[NoFog](https://www.curseforge.com/minecraft/mc-mods/nofog)' ... *works with Sodium and Sodium Extra, and sowwy for the irrelevant topic here*

**Comment by Julienraptor01** [comment] 2023-02-11 21:45
Duplicate of #350

**Comment by Madis0** [comment] 2023-02-11 21:50
Closed for being a duplicate request, and this fix is already present in FO via Debugify.

**Closed by Madis0** 2023-02-11 21:50 UTC
Labels: mod

**Comment by Izov4r** [comment] 2023-02-25 14:33
@Madis0 Oh ok, then I don't need to add this mod to my mods folder.
