### ISSUE TITLE
AppleSkin

### ISSUE THREAD

**Issue by orionzleon** [Fabulously-Optimized/fabulously-optimized#692] opened 2023-07-24 18:00 UTC
### CurseForge link

https://www.curseforge.com/minecraft/mc-mods/appleskin

### CurseForge Mod Distribution

Allowed

### Modrinth link

https://modrinth.com/mod/appleskin

### Source/other link

https://github.com/squeek502/AppleSkin

### Mod file size

1.01 MB

### License

(any other license)

### What it does

Project description:
> Adds various food-related HUD improvements. This is a mostly client-side mod, but it needs to be on the server in order to display accurate saturation/exhaustion values on the client.

This mod adds the ability to see how much saturation you have in the HUD. It also shows how much hunger and saturation food will restore when you eat it.

### Why should it be in the modpack

This mod does not change too much of the game. It adds a tooltip for food items, and shows your current saturation level. This is a QoL feature.

### Why shouldn't it be in the modpack

It shows you how much saturation you have. This is not a vanilla feature. Even so, users who do not like this feature can go into Mod Menu and turn off the mod.

**Comment by Madis0** [comment] 2023-07-24 18:46
Duplicate of #606

**Closed by Madis0** 2023-07-24 18:46 UTC
Labels: mod
