### ISSUE TITLE
Distant Horizons Mod - 1.18.2 + 1.19

### ISSUE THREAD

**Issue by arichorn** [Fabulously-Optimized/fabulously-optimized#429] opened 2022-07-30 11:06 UTC
### CurseForge link

https://www.curseforge.com/minecraft/mc-mods/distant-horizons

### CurseForge Mod Distribution

Allowed

### Modrinth link

https://modrinth.com/mod/distanthorizons

### Source/other link

https://gitlab.com/jeseibel/minecraft-lod-mod

### Mod file size

1.18.2 = 2.46 MB | 1.19 = 2.49 MB

### What it does

it add simplified terrain past Minecraft's default view distance to improve performance and allow for longer draw distances. 

### Why should it be in the modpack

It’s pretty much a performance mod and also giving you a higher render distance.

### Why shouldn't it be in the modpack

It is in Alpha but I don’t know when they will actually fully release it and if any other performance mods mess with the render distance then I would not simply add it.

### Categories

Performance optimization, Graphics optimization

**Comment by Madis0** [comment] 2022-07-30 11:07
Duplicate of #240

**Closed by Madis0** 2022-07-30 11:07 UTC
Labels: mod

**Comment by arichorn** [comment] 2022-07-30 11:09
No problem! And sorry that I didn’t know about the duplicate!
