### ISSUE TITLE
Enhanced Attack Indicator

### ISSUE THREAD

**Issue by RaptaG** [Fabulously-Optimized/fabulously-optimized#249] opened 2022-03-01 15:32 UTC
### Mod name

Enhanced Attack Indicator

### Curseforge link

https://www.curseforge.com/minecraft/mc-mods/enhanced-attack-indicator

### Other links

Modrinth: https://modrinth.com/mod/enhanced-attack-indicator

GitHub: https://github.com/Minenash/Enhanced-Attack-Indicator

### What it does

Gives the attach indicator more uses

### Why should it be in the modpack

Useful for time calculation of some things in a very vanilla way

### Why shouldn't it be in the modpack

Why isn't it already 😂

### Categories

New feature

**Comment by Madis0** [comment] 2022-03-01 15:35
Duplicate of #50. Please search before suggesting.

**Closed by Madis0** 2022-03-01 15:35 UTC
Labels: mod
