### ISSUE TITLE
Better Biome Blend

### ISSUE THREAD

**Issue by blablakali** [Fabulously-Optimized/fabulously-optimized#558] opened 2022-12-31 13:07 UTC
### CurseForge link

https://www.curseforge.com/minecraft/mc-mods/better-biome-blend

### CurseForge Mod Distribution

Allowed

### Modrinth link

https://modrinth.com/mod/better-biome-blend

### Mod file size

48.38 KB

### License

(any other license)

### What it does

It improves biome blend performance, & allows upto 23x23 biome blending radius.

### Why should it be in the modpack

- Better Performance
- Enhanced biome blend

### Why shouldn't it be in the modpack

1.18+ versionnns can only use 23x23 radius.

**Comment by Madis0** [comment] 2022-12-31 13:09
Duplicate of #353

**Closed by Madis0** 2022-12-31 13:09 UTC
Labels: mod
