### ISSUE TITLE
Simple Discord

### ISSUE THREAD

**Issue by NotRabug50** [Fabulously-Optimized/fabulously-optimized#708] opened 2023-08-26 16:32 UTC
### CurseForge link

https://www.curseforge.com/minecraft/mc-mods/simple-discord-rpc

### CurseForge Mod Distribution

Allowed

### Modrinth link

https://modrinth.com/mod/simple-discord-rpc

### Mod file size

665 KB

### License

All Rights Reserved / ARR

### What it does

It sends RPC to discord and shows what are you doing minecraft in example playing in xx world etc.

### Why should it be in the modpack

yea its not affects gameplay just a cool feature

### Why shouldn't it be in the modpack

idk

**Comment by Madis0** [comment] 2023-08-26 16:59
Duplicate of #191 and the the rejection reasoning is on https://github.com/Fabulously-Optimized/fabulously-optimized/issues/191#issuecomment-991890079

**Closed by Madis0** 2023-08-26 16:59 UTC
Labels: mod
