### ISSUE TITLE
Dashloader

### ISSUE THREAD

**Issue by code004Accepted** [Fabulously-Optimized/fabulously-optimized#542] opened 2022-12-11 07:24 UTC
### CurseForge link

https://www.curseforge.com/minecraft/mc-mods/dashloader

### CurseForge Mod Distribution

Allowed

### Modrinth link

https://modrinth.com/mod/dashloader

### Source/other link

https://github.com/TeamQuantumFusion/DashLoader

### Mod file size

5.58MB

### License

(any other license)

### What it does

Greatly decreases loading speed (starting at the second time)

### Why should it be in the modpack

Increases experience

### Why shouldn't it be in the modpack

Using this mod will skip the vanilla loading screen and the window may appear to be "Not Responding".

Also, the mod currently does not support 1.19.3.

**Comment by Madis0** [comment] 2022-12-11 07:26
Duplicate of #48. You can comment there with your benchmarks if you can actually see any improvement, because I couldn't.

**Closed by Madis0** 2022-12-11 07:26 UTC
Labels: mod

**Comment by code004Accepted** [comment] 2022-12-11 12:00
Sure. I was at first posting for another mod so I forgot to go through the past issues before posting. Sorry for the inconvenience.

I may post about the mod fastload later this week cause I'm investigating about a glitch and I'll post a new issue when ready.

I might record a video later and upload it to [Issue 48](https://github.com/Fabulously-Optimized/fabulously-optimized/issues/48). Thanks for the help!

**Comment by Madis0** [comment] 2022-12-11 12:06
> I may post about the mod fastload later this week

#365 😄

I am aware of most of the performance mods that are available at the moment, there is just either not enough testing done on them or the testing results were negative (not a improvement), so any additional testing is always helpful.

**Comment by code004Accepted** [comment] 2022-12-11 12:25
Sure. I'd love to help with testing and I will hopefully do more of them in the future.

btw, I did perform that search on fastload... I think my Microsoft Editor extension is messing with the github search filter...
