### ISSUE TITLE
Add Wavey Capes please

### ISSUE THREAD

**Issue by Mark6O9** [Fabulously-Optimized/fabulously-optimized#745] opened 2023-10-16 12:44 UTC
### CurseForge link

https://www.curseforge.com/minecraft/mc-mods/waveycapes

### CurseForge Mod Distribution

Allowed

### Modrinth link

https://modrinth.com/mod/wavey-capes

### Source/other link

https://github.com/tr7zw/WaveyCapes

### Mod file size

321.3 KB

### License

(any other license)

### What it does

It turns the static cape model into a physics based cloth that blows in the wind and moves more like how a cape would in real life

### Why should it be in the modpack

It's a very neat and very cool mod that's can be toggled on or off, is compatible with half of every cape mod out there, and It's a client side mod

### Why shouldn't it be in the modpack

I'm unaware if it could effect performance or not but it might since it's physics based but it also might not work like that since in first person you're not seeing it

**Comment by Madis0** [comment] 2023-10-16 12:46
Duplicate of #560

**Closed by Madis0** 2023-10-16 12:46 UTC
Labels: mod
