### ISSUE TITLE
Mod request - DashLoader

### ISSUE THREAD

**Issue by Zetvue** [Fabulously-Optimized/fabulously-optimized#275] opened 2022-03-27 03:24 UTC
### Mod name

DashLoader

### Curseforge link

https://www.curseforge.com/minecraft/mc-mods/dashloader

### Other links

https://modrinth.com/mod/dashloader
https://github.com/alphaqu/DashLoader

### What it does

From the Modrinth page:
**This mod improves Minecraft client asset loading times about 6x by caching all of the game's content. This cache can be loaded in less than 2 seconds in most scenarios. The improvements are even bigger the more modded Minecraft is as it's highly efficient and scalable. Furthermore its 100% multithreaded so all of your cores will be active (Minecraft uses at most 2).**

### Why should it be in the modpack

It launches insanely quick and barely impacts anything. And from [here](https://github.com/MicrocontrollersDev/MigratingToLatest/blob/main/README.md#will-never-be-supported), for Smooth Boot:
<html><body>

Smooth Boot | While Smooth Boot does great at decreasing startup time, it is no  match for LazyDFU and DashLoader. Smooth Boot will also cause a decrease  in performance for several minutes after startup according to some  reports.
-- | --

</body>
</html>

### Why shouldn't it be in the modpack

From the Modrinth page: **Mod support is difficult to pin down. Most mods should work fine, but when they don't they are often horrifically broken with many models missing.**
Other than that, I haven't seen any other issues with it. Feel free to let me know if issues that stop this mod from being included are here.

### Categories

Replaces an existing mod

### Additional details

I have searched for DashLoader and it was back in April, 2021. The mod has massively improved since then, so I think it should be included.

**Comment by Madis0** [comment] 2022-03-27 04:40
Duplicate of #48. If you think it has massively improved, do post your (new) arguments there. 

For counter-arguments, though: 3.0.0 was a major rewrite, yet 3.0.1 was still created to "fix everything". Don't know what it means code-wise, but it again it doesn't instill confidence.

**Closed by Madis0** 2022-03-27 04:40 UTC
Labels: mod
