### ISSUE TITLE
[mod request] Essential

### ISSUE THREAD

**Issue by Merith-TK** [Fabulously-Optimized/fabulously-optimized#220] opened 2022-01-05 04:32 UTC
### Mod name

essential

### Other links

**Official:** https://essential.gg/

### What it does

adds QOL clientside features to enhance multiplayer expiriences
* Cosmetics
* Friends List and ingame direct messaging to other users
* Peer 2 Peer multiplayer, invite a friend to your single player world!
* Allows switching minecraft accounts in game

### Why should it be in the modpack

its overall loved by everyone who I have introduced to it, and it doesnt add anything overly extra to the game
![image](https://user-images.githubusercontent.com/10422110/148159353-72311db3-78c6-43a6-be81-6b44c7d1fc4f.png)

### Why shouldn't it be in the modpack

it relies on external services outside of the game, and requires users to accept an EULA at first launch with the mod

### Categories

New feature

**Comment by Madis0** [comment] 2022-01-05 05:32
Duplicate of #166, post any arguments you have there.

**Closed by Madis0** 2022-01-05 05:32 UTC
Labels: mod
