### ISSUE TITLE
DashLoader

### ISSUE THREAD

**Issue by KOMPuteRSH4IK** [Fabulously-Optimized/fabulously-optimized#421] opened 2022-07-23 11:35 UTC
### CurseForge link

https://www.curseforge.com/minecraft/mc-mods/dashloader

### Modrinth link

https://modrinth.com/mod/dashloader

### Source/other link

https://github.com/alphaqu/DashLoader

### Mod file size

5.62 MB

### What it does

This mod accelerates the Minecraft Asset Loading system by caching all of its content, This leads to a much faster game load. It does this by caching all of its content on first launch and on next launch loading back that exact cache. The cache loading is hyper fast and scalable which utilises your entire system.

### Why should it be in the modpack

Because it speeds up the loading time of Minecraft by many times.

### Why shouldn't it be in the modpack

DashLoader has been known to be incompatible with a lot of mods. DashLoader 3.0 has massively improved compatibility by not forcing mod developers to add explicit support to make their assets cachable. This means that DashLoader will load assets normally for mod assets that cannot be cached. While this improves mod compatibility it hurts speed as the minecraft loading system is quite slow.

### Categories

Performance optimization

**Comment by Madis0** [comment] 2022-07-23 11:43
Duplicate of #48 
If you have new arguments, post them there.

**Closed by Madis0** 2022-07-23 11:43 UTC
Labels: mod
