### ISSUE TITLE
Chat tooltips are offset in 6.2.2

### ISSUE THREAD

**Issue by GrauerDrach** [Fabulously-Optimized/fabulously-optimized#909] opened 2024-11-05 20:21 UTC
### Describe the bug

Offset of the interactive link.
1. Screenshot on the modpack
2. Screenshot on vanilla

### Modpack version

6.2.2 for 1.21.1

### Launcher

Modrinth App

### Confirm

- [X] This bug report is about an issue with the modpack itself, I have not modified the mods nor added any resource packs. If this is not the case, I know that I should post the issue to modpack's Discord support channel instead.

### Additional context

![2024-11-06_00 37 56](https://github.com/user-attachments/assets/5d72cd52-f32e-4b9d-a3df-aa9da6a5b9c9)
![2024-11-06_01 12 36](https://github.com/user-attachments/assets/ef328f24-5935-44ca-80d7-c2d031032e17)

**Comment by Madis0** [comment] 2024-11-05 20:26
Thanks, that bug is caused by Controlify. No known fix yet, but it has been reported.

**Comment by Madis0** [comment] 2024-11-20 18:56
Fixed in v6.2.3.

**Closed by Madis0** 2024-11-20 18:56 UTC
Labels: bug
