### ISSUE TITLE
Sodium Shadowy Path Blocks Mods

### ISSUE THREAD

**Issue by KOMPuteRSH4IK** [Fabulously-Optimized/fabulously-optimized#402] opened 2022-07-07 07:43 UTC
### CurseForge link

https://www.curseforge.com/minecraft/mc-mods/sodium-shadowy-path-blocks

### What it does

Sodium Shadowy Path Blocks (or SSPB for short) is an addon to Sodium that reintroduces vanilla-like smooth lighting to non-fluid non-full blocks (e.g. dirt paths and how they have dark shading when directly next to a full block), as Sodium removes this (or rather, fixes this, as it's technically a bug).

This was mainly made because I liked the shadowyness of the vanilla dirt paths, hence the name.

This lighting is not exactly the same as vanilla, only vanilla-like, as the way I'm doing this is entirely based on Sodium's smooth lighting code.

Requires Sodium (duh) and only has an effect with smooth lighting enabled.

Not associated with Sodium or CaffeineMC. 

### Why should it be in the modpack

Mod added shadows for blocks in Minecraft 

### Why shouldn't it be in the modpack

I do not know

### Categories

Works like OptiFine/Bedrock Edition/Forge/etc

**Comment by Madis0** [comment] 2022-07-07 07:45
Duplicate of #204

**Closed** 2022-07-07 11:40 UTC
Labels: duplicate, mod, rejected
