### ISSUE TITLE
Cosmetica

### ISSUE THREAD

**Issue by Meow-purr** [Fabulously-Optimized/fabulously-optimized#736] opened 2023-09-30 00:01 UTC
### CurseForge Mod Distribution

Unknown

### Modrinth link

https://modrinth.com/mod/cosmetica

### Source/other link

https://github.com/Cosmetica-cc/Cosmetica

### Mod file size

523.87 kilobytes

### License

(any other license)

### What it does

adds cosmeticcs

### Why should it be in the modpack

to add more cosmeticas than he capes mod while being vanila like

### Why shouldn't it be in the modpack

no realy any other than remember 

### Additional details

get rid of the capes mod if you add this and edit config to add support for capes fromm capes mod and optifine and evrywere else

**Comment by Meow-purr** [comment] 2023-09-30 00:01
closing as dupe of #315

**Comment by osfanbuff63** [comment] 2023-09-30 00:13
Yeah, duplicate of #315

**Closed by osfanbuff63** 2023-09-30 00:13 UTC
Labels: mod
