### ISSUE TITLE
CalcMod

### ISSUE THREAD

**Issue by Josephloang** [Fabulously-Optimized/fabulously-optimized#728] opened 2023-09-19 19:42 UTC
### CurseForge link

https://www.curseforge.com/minecraft/mc-mods/calcmod

### CurseForge Mod Distribution

Allowed

### Modrinth link

https://modrinth.com/mod/calcmod

### Mod file size

599 KB

### License

(any other license)

### What it does

A calculator in the mc chat, uses /calc (input).
has extra useful features like calculating the nether coords of a given position, items needed to craft stuff, and the storage utils etc... those are the ones i use most.

### Why should it be in the modpack

I looked at all the other calculator mods, but picked this one. it's genuinely really useful to a more technical minecrafter. its user friendly, and unintrusive. would fit in FO perfectly as it is a vanilla QOL mod

heres the modrinth link again, theres a pretty good description of the features there:
[https://modrinth.com/mod/calcmod](https://modrinth.com/mod/calcmod)

### Why shouldn't it be in the modpack

sometimes it's hard to remember to use the mod, but after a while it becomes easier to use

**Comment by Madis0** [comment] 2023-09-19 19:44
Duplicate of #706

**Closed by Madis0** 2023-09-19 19:44 UTC
Labels: mod

**Comment by Kichura** [comment] 2023-09-29 16:57
Commenting on this since OP has changed to title to "OptiFabric" - This will not be added for a number of reasons:

1. OptiFine is known for breaking multiple mods when replacing sodium with the other,
2. OptiFine is ARR which essentially means Madis needs explicit permission from creator to use it at all,
3. OptiFine has garbage FPS earnings from benchmarkings and therefore is only """good""" on potato PCs,
4. OptiFabric by itself is known for breaking very easily when new updates come out and therefore is basically not worth shipping into FO as-is.
