### ISSUE TITLE
Mixin Conflict Helper

### ISSUE THREAD

**Issue by isXander** [Fabulously-Optimized/fabulously-optimized#411] opened 2022-07-12 11:38 UTC
### CurseForge link

https://curseforge.com/minecraft/mc-mods/mixin-conflict-helper

### CurseForge Mod Distribution

Allowed

### Modrinth link

https://modrinth.com/mod/mixin-conflict-helper

### Source/other link

https://github.com/isXander/MixinConflictHelper

### What it does

Catches crashes due to Mixin conflicts and provides a user-friendly error explaining what two mods are causing the crash, directing them to the respective issues page.

### Why should it be in the modpack

FO is described as a base for users or other modpacks to expand upon. This provides users or developers an easy way to diagnose issues if they have any. Especially useful for people who can't read stacktraces. Also allows users to continue to use the modpack when they have such an issue.

### Why shouldn't it be in the modpack

Relies on nasty swing GUI. Might cause issues on MacOS, untested.

### Categories

New feature

**Comment by Madis0** [comment] 2022-07-12 11:42
Duplicate of #410 😆

**Closed by Madis0** 2022-07-12 11:42 UTC
Labels: mod
