### ISSUE TITLE
Exordium

### ISSUE THREAD

**Issue by LittleH00** [Fabulously-Optimized/fabulously-optimized#506] opened 2022-11-01 14:08 UTC
### CurseForge link

https://www.curseforge.com/minecraft/mc-mods/exordium

### CurseForge Mod Distribution

Not allowed

### Modrinth link

https://modrinth.com/mod/exordium

### Mod file size

130.18 KB

### License

(any other license)

### What it does

It essentially Renders GUI at a lower framerate, to allow for more CPU/GPU room for rendering the world.

### Why should it be in the modpack

I would consider Exordium to be a great candidate to add to FO, and adds to the main goal of the modpack, on the surface, it doesn't add much, yet the performance is boosted even further. Plus, it has compatibility with a lot of the mods already in FO. I've been using this mod with FO for the past half-month, and a bunch of other (not performance based) mods, yet it's remained stable. 

### Why shouldn't it be in the modpack

However, that said, the compatibility doesn't stretch everywhere, many developers may have designed things with that GUI FPS in mind, therefore with certain mods (a good example being Xaero's World Map) or just in general, there can be quite a few visual and/or compatibility issues in GUI, whether it be blinking, failing to render, or failing function properly at all.
Also, this mod has no plans of backports, due to limitations in the game's engine.

That said, keep in mind that if there is a compatibility issue, you can always report it on their GitHub, so if there's any problems with mods in FO, there is a possibility of the problem being solved.

### Additional details

Quite frankly, I am slightly surprised noone has noticed this mod yet, it seems to check all the boxes for a good mod for FO, while I admit, distribution not being allowed is a problem, there is always potential to collaborate with tr9zw (The developer of the mod) in the future.

**Comment by Madis0** [comment] 2022-11-01 14:09
Duplicate of #398

**Closed by Madis0** 2022-11-01 14:09 UTC
Labels: mod
