### ISSUE TITLE
Bobby is a mod similar to Farsight.

### ISSUE THREAD

**Issue by Jeberdog** [Fabulously-Optimized/fabulously-optimized#673] opened 2023-06-26 01:42 UTC
### CurseForge Mod Distribution

None

### Modrinth link

https://modrinth.com/mod/bobby

### Mod file size

782.92 KiB

### License

(any other license)

### What it does

Bobby is a Minecraft mod which allows for render distances greater than the server's view-distance setting.

### Why should it be in the modpack

A good alternative to Farsight Mod because it is available in Modrinth.

### Why shouldn't it be in the modpack

Haven't been tested alongside other mods in the Modpack.

### Additional details

This is my first time doing this. Thanks for this Modpack!

**Comment by Madis0** [comment] 2023-06-26 04:10
Duplicate of #556

**Closed by Madis0** 2023-06-26 04:10 UTC
Labels: duplicate, mod
