### ISSUE TITLE
Add Screenshot to Clipboard mod

### ISSUE THREAD

**Issue by joex92** [Fabulously-Optimized/fabulously-optimized#235] opened 2022-02-01 15:04 UTC
### Mod name

Screenshot to Clipboard

### Curseforge link

https://www.curseforge.com/minecraft/mc-mods/screenshot-to-clipboard-fabric

### What it does

copy the taken screenshot by F2 to the clipboard, that way it's easier to share the screenshot.

### Why should it be in the modpack

it's super convenient when sharing screenshots

### Why shouldn't it be in the modpack

I honestly don't find any downsides, it's just super useful...

### Categories

New feature

**Comment by Madis0** [comment] 2022-02-01 15:05
The downside is user expectations, I don't want to override users clipboard while they are not aware of it. Therefore this is more suitable for adding manually (see wiki for tutorial).
Duplicate of #208

**Closed by Madis0** 2022-02-01 15:05 UTC
Labels: mod
