### ISSUE TITLE
DashLoader

### ISSUE THREAD

**Issue by OmriOn** [Fabulously-Optimized/fabulously-optimized#489] opened 2022-09-30 10:41 UTC
### CurseForge link

https://www.curseforge.com/minecraft/mc-mods/dashloader

### CurseForge Mod Distribution

Allowed

### Modrinth link

https://modrinth.com/mod/dashloader

### Source/other link

https://github.com/TeamQuantumFusion/DashLoader

### Mod file size

5.58 MiB

### License

(any other license)

### What it does

 This mod accelerates the Minecraft Asset Loading system by caching all of its content, This leads to a much faster game load. It does this by caching all of its content on the first launch and next launch loading back that exact cache. The cache loading is hyper-fast and scalable which utilizes your entire system. 

### Why should it be in the modpack

Dashloader improves the experience by making load times very fast and does not interfere with gameplay at all, staying vanilla-like.

### Why shouldn't it be in the modpack

The DashLoader cache can become very big and take up some space, if used a lot

**Comment by osfanbuff63** [comment] 2022-09-30 10:51
Duplicate of #48

**Closed** 2022-09-30 10:53 UTC
Labels: mod
