### ISSUE TITLE
BetterF3

### ISSUE THREAD

**Issue by Sir-Crazynut** [Fabulously-Optimized/fabulously-optimized#829] opened 2024-04-08 12:52 UTC
### CurseForge Mod Distribution

Unknown

### Modrinth link

https://modrinth.com/mod/betterf3

### Source/other link

https://github.com/TreyRuffy/BetterF3

### Mod file size

458.72 KB

### License

(any other license)

### What it does

BetterF3 is a mod that replaces Minecraft's original debug HUD with a highly customizable, more human-readable HUD. You can customize colors, position, add spacings, and more.

### Why should it be in the modpack

The makes the F3 menu much more usable and enjoyable while not actually changing the function. Especially when playing on servers, betterF3 allows you to customize your F3 menu to fit around on on-screen gui's, etc, allowing you to better contemplate all the frames you get from using the modpack

### Why shouldn't it be in the modpack

Not available on Curseforge as far as I could see

### Additional details

Any time I make a new profile on the Modrinth Launcher, I start with FO and this is the first mod I add

**Comment by TheBossMagnus** [comment] 2024-04-08 13:25
Duplicate of #639

**Comment by TheBossMagnus** [comment] 2024-04-08 14:33
Duplicate of #639

**Closed by TheBossMagnus** 2024-04-08 14:33 UTC
Labels: duplicate, mod
