### ISSUE TITLE
Exordium

### ISSUE THREAD

**Issue by Woodgoldtwo** [Fabulously-Optimized/fabulously-optimized#495] opened 2022-10-16 10:29 UTC
### CurseForge link

https://www.curseforge.com/minecraft/mc-mods/exordium

### CurseForge Mod Distribution

Not allowed

### Modrinth link

https://modrinth.com/mod/exordium

### Source/other link

https://github.com/tr7zw/Exordium

### Mod file size

130.18 KB

### License

(any other license)

### What it does

Features:
- Render the gui at a lower framerate (configurable in the settings)
- Speedup gui rendering during fade animations (configurable in the settings)
- Render screens at a lower framerate (configurable in the settings)
- Pre-render sign text(glowing signs render multiple times each frame in vanilla)
- Buffer full screen name-tags to reduce the amount of draw calls in game lobbies

(this was copied from the curseforge page)

### Why should it be in the modpack

It renders the GUI at a lower fixed framerate, freeing up the CPU and GPU time for more important things such as world rendering

### Why shouldn't it be in the modpack

The mod is still in beta and might have undocumented incompatibilities with other mods

### Additional details

The mod is tested and confirmed to be working with:
- Sodium
- Iris
- AppleSkin
- Better Ping Display
- Chat Heads
- Detail Armor Bar
- WTHIT
- JourneyMap
- ToroHealth Damage Indicators
- BetterF3
- Roughly Enough Items (small visual issue with the rendering of enchanted items in REI's interface)

**Comment by Madis0** [comment] 2022-10-16 10:32
Duplicate of #398

**Closed by Madis0** 2022-10-16 10:32 UTC
Labels: mod
