### ISSUE TITLE
Ok Boomer

### ISSUE THREAD

**Issue by RozeFound** [Fabulously-Optimized/fabulously-optimized#753] opened 2023-10-24 06:00 UTC
### CurseForge link

https://www.curseforge.com/minecraft/mc-mods/ok-boomer-zoom

### CurseForge Mod Distribution

Allowed

### Modrinth link

https://modrinth.com/mod/ok-boomer

### Source/other link

https://github.com/wisp-forest/ok-boomer

### Mod file size

50.01 KiB

### License

(any other license)

### What it does

Zoom into anything by pressing customizable keybind (default `c`)
Zoom into screens (inventory, main menu, and anything else basically) with `ctrl+shift+c`

### Why should it be in the modpack

Smooth and customizable zoom
Zoom into screens (useful for streamers)
Fast update cycle

### Why shouldn't it be in the modpack

New dependency (owo-lib)

### Additional details

Creating new issue because modpack author purposefully ignoring the old one.
At least place it in some alpha idk, and afterwards ask people what they liked more.

**Comment by Madis0** [comment] 2023-10-24 06:03
Duplicate of #577

**Comment by RozeFound** [comment] 2023-10-24 06:04
That's rude

**Closed by Madis0** 2023-10-24 06:03 UTC
Labels: mod

**Comment by Madis0** [comment] 2023-10-24 06:08
![83m677](https://github.com/Fabulously-Optimized/fabulously-optimized/assets/8611110/c7468036-01ef-40e8-8daf-d9da6b861eb8)

**Comment by RozeFound** [comment] 2023-10-24 06:08
Don't worry, I'll create a new one in a short while

**Comment by Madis0** [comment] 2023-10-24 06:10
Spam is not a solution. Good, proven arguments are.
